#pragma once 
// Algorithm header to reference 
#include <filter/algos/Akaze.h>
#include <filter/algos/AlgoExample_1.h>
#include <filter/algos/AverageColor.h>
#include <filter/algos/BilateralFilter.h>
#include <filter/algos/Binary.h>
#include <filter/algos/BinaryAdaptive.h>
#include <filter/algos/Blur.h>
#include <filter/algos/Brightness.h>
#include <filter/algos/Canny.h>
#include <filter/algos/ClosestColor.h>
#include <filter/algos/ComputeRegularGrid.h>
#include <filter/algos/Contrast.h>
#include <filter/algos/Crop.h>
#include <filter/algos/Cropper.h>
#include <filter/algos/DelegateStreamingFilter.h>
#include <filter/algos/DetectCirclesFilter.h>
#include <filter/algos/Dilate.h>
#include <filter/algos/DrawCircles.h>
#include <filter/algos/EncodeDataFilter.h>
#include <filter/algos/Equalize.h>
#include <filter/algos/EqualizeAdaptive.h>
#include <filter/algos/Erode.h>
#include <filter/algos/ExclusionZoneMaskFilter.h>
#include <filter/algos/ExctractSubImage.h>
#include <filter/algos/ExtractPatternCrops.h>
#include <filter/algos/ExtractPatternSource.h>
#include <filter/algos/FaceDetection.h>
#include <filter/algos/FaceLandmark.h>
#include <filter/algos/FilePatternFilter.h>
#include <filter/algos/FingerPrint.h>
#include <filter/algos/FingerPrintMinutia.h>
#include <filter/algos/FingerprintMinutiae.h>
#include <filter/algos/Gaussian.h>
#include <filter/algos/Grayscale.h>
#include <filter/algos/HideCircles.h>
#include <filter/algos/HOGLiveDetector.h>
#include <filter/algos/HOGLiveTrainer.h>
#include <filter/algos/Homography.h>
#include <filter/algos/IDPlateCropper.h>
#include <filter/algos/IDPlateIdentifier.h>
#include <filter/algos/IDPlateRectifier.h>
#include <filter/algos/Invert.h>
#include <filter/algos/Kmeans.h>
#include <filter/algos/Latch.h>
#include <filter/algos/LatchDebug.h>
#include <filter/algos/Median.h>
#include <filter/algos/OrderCircles.h>
#include <filter/algos/OutputImage.h>
#include <filter/algos/OutputRawDataFilter.h>
#include <filter/algos/OverlayFilter.h>
#include <filter/algos/OverlayMatFilter.h>
#include <filter/algos/PPOC.h>
#include <filter/algos/PythonFilter.h>
#include <filter/algos/ReshapeImage.h>
#include <filter/algos/Resize.h>
#include <filter/algos/ResizePattern.h>
#include <filter/algos/ResultFilter.h>
#include <filter/algos/RootFilter.h>
#include <filter/algos/RotateImage.h>
#include <filter/algos/ShowImage.h>
#include <filter/algos/ShowVideo.h>
#include <filter/algos/StreamResultFilter.h>
#include <filter/algos/Surf.h>
#include <filter/algos/IDPlate\IDPlateTools.h>
#include <filter/algos/yolo\ObjectRecognitionYolo.h>
#include <filter/datasource/ImageDataSource.h>
#include <filter/datasource/VideoDataSource.h>
