#!/bin/bash
set -eu

header_path="$(readlink -f "$1")"
header_dir="${header_path%/*}"
cmp_path="${header_path}.cmp"

function update_header()
{
  echo "updating $header_path"
  cp -- "$cmp_path" "$header_path"
}

function update_cmp()
{
  echo -e "// This file is automatically generated by CMake. Do not edit.\n#pragma once" > "$cmp_path"
  pushd "$header_dir" >/dev/null
    find algos \( -name '*.h' -o -name '*.hpp' \) -type f -printf "#include <filter/%p>\n" | sort -u >> "$cmp_path"
  popd >/dev/null
}

function maybe_update_header()
{
  if [[ ! -e "$header_path" ]]
  then
    update_header
    exit 0
  fi

  cmp_cmd=''
  if command -v cmp >/dev/null
  then
    cmp_cmd=cmp
  elif command -v diff >/dev/null
  then
    cmp_cmd=diff
  fi

  if [[ -z $cmp_cmd ]]
  then
    header_contents="$(< "$header_path")"
    cmp_contents="$(< "$cmp_path")"
    if [[ $header_contents != $cmp_contents ]]
    then
      update_header
      exit 0
    fi
  else
    if ! "$cmp_cmd" "$header_path" "$cmp_path" >/dev/null
    then
      update_header
      exit 0
    fi
  fi
  echo "no changes in $header_path"
}

update_cmp
maybe_update_header
