var searchData=
[
  ['canny',['Canny',['../d8/de8/classfilter_1_1_algos_1_1_canny.html',1,'filter::Algos']]],
  ['capturevideo',['CaptureVideo',['../d4/d6c/class_capture_video.html',1,'']]],
  ['capturevideofactory',['CaptureVideoFactory',['../d6/d4b/class_capture_video_factory.html',1,'']]],
  ['client',['Client',['../d2/d35/classhttp_1_1_client.html',1,'http']]],
  ['client_3c_20http_20_3e',['Client&lt; HTTP &gt;',['../d4/da7/classhttp_1_1_client_3_01_h_t_t_p_01_4.html',1,'http']]],
  ['clientbase',['ClientBase',['../d2/d7e/classhttp_1_1_client_base.html',1,'http']]],
  ['clientbase_3c_20http_20_3e',['ClientBase&lt; HTTP &gt;',['../d2/d7e/classhttp_1_1_client_base.html',1,'http']]],
  ['closestcolor',['ClosestColor',['../d1/d1c/classfilter_1_1algos_1_1_closest_color.html',1,'filter::algos']]],
  ['color',['Color',['../d7/d65/structfilter_1_1algos_1_1_closest_color_1_1_color.html',1,'filter::algos::ClosestColor']]],
  ['commandexecuter',['CommandExecuter',['../d8/dbb/classhttp_1_1_command_executer.html',1,'http']]],
  ['commandmanager',['CommandManager',['../df/d3a/classhttp_1_1_command_manager.html',1,'http']]],
  ['comparebyderiv',['CompareByDeriv',['../d8/de0/structfilter_1_1algos_1_1_i_d_plate_1_1_compare_by_deriv.html',1,'filter::algos::IDPlate']]],
  ['composer',['Composer',['../de/d80/classfilter_1_1data_1_1_composer.html',1,'filter::data']]],
  ['comprectsbypos',['CompRectsByPos',['../d3/df9/structfilter_1_1algos_1_1_i_d_plate_1_1_comp_rects_by_pos.html',1,'filter::algos::IDPlate']]],
  ['concurrentqueue',['ConcurrentQueue',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20cv_3a_3amat_20_3e',['ConcurrentQueue&lt; cv::Mat &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20filter_3a_3aalgos_3a_3alatch_3a_3amatchcontainer_20_3e',['ConcurrentQueue&lt; filter::algos::Latch::MatchContainer &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20filter_3a_3adata_3a_3adata_20_3e',['ConcurrentQueue&lt; filter::data::Data &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20filter_3a_3adata_3a_3aimagedata_20_3e',['ConcurrentQueue&lt; filter::data::ImageData &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20filter_3a_3adata_3a_3apatterndata_20_3e',['ConcurrentQueue&lt; filter::data::PatternData &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20filter_3a_3adata_3a_3asquarecrop_20_3e',['ConcurrentQueue&lt; filter::data::SquareCrop &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['concurrentqueue_3c_20std_3a_3avector_3c_20cv_3a_3apoint_20_3e_20_3e',['ConcurrentQueue&lt; std::vector&lt; cv::Point &gt; &gt;',['../d5/df8/classcore_1_1queue_1_1_concurrent_queue.html',1,'core::queue']]],
  ['conductor',['Conductor',['../dd/d8e/classorchestrator_1_1_conductor.html',1,'orchestrator']]],
  ['config',['Config',['../da/d6a/classhttp_1_1_server_base_1_1_config.html',1,'http::ServerBase&lt; socket_type &gt;::Config'],['../d7/d5d/struct_f_fmpeg_opencv_decoder_1_1config.html',1,'FFmpegOpencvDecoder::config'],['../df/de9/classhttp_1_1_config.html',1,'http::Config'],['../d1/d7e/classhttp_1_1_client_base_1_1_config.html',1,'http::ClientBase&lt; socket_type &gt;::Config']]],
  ['connexdata',['ConnexData',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20din_2c_20din_20_3e',['ConnexData&lt; Din, Din &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20dout_2c_20dout_20_3e',['ConnexData&lt; Dout, Dout &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3adata_2c_20filter_3a_3adata_3a_3adata_20_3e',['ConnexData&lt; filter::data::Data, filter::data::Data &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3adata_2c_20filter_3a_3adata_3a_3aimagedata_20_3e',['ConnexData&lt; filter::data::Data, filter::data::ImageData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3aimagearraydata_2c_20filter_3a_3adata_3a_3aimagearraydata_20_3e',['ConnexData&lt; filter::data::ImageArrayData, filter::data::ImageArrayData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3aimagearraydata_2c_20filter_3a_3adata_3a_3aimagedata_20_3e',['ConnexData&lt; filter::data::ImageArrayData, filter::data::ImageData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3aimagearraydata_2c_20filter_3a_3adata_3a_3asquarecrop_20_3e',['ConnexData&lt; filter::data::ImageArrayData, filter::data::SquareCrop &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3aimagedata_2c_20filter_3a_3adata_3a_3aimagearraydata_20_3e',['ConnexData&lt; filter::data::ImageData, filter::data::ImageArrayData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3aimagedata_2c_20filter_3a_3adata_3a_3aimagedata_20_3e',['ConnexData&lt; filter::data::ImageData, filter::data::ImageData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3aimagedata_2c_20filter_3a_3adata_3a_3apatterndata_20_3e',['ConnexData&lt; filter::data::ImageData, filter::data::PatternData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3apatterndata_2c_20filter_3a_3adata_3a_3aimagedata_20_3e',['ConnexData&lt; filter::data::PatternData, filter::data::ImageData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdata_3c_20filter_3a_3adata_3a_3apatterndata_2c_20filter_3a_3adata_3a_3apatterndata_20_3e',['ConnexData&lt; filter::data::PatternData, filter::data::PatternData &gt;',['../dc/d36/classfilter_1_1data_1_1_connex_data.html',1,'filter::data']]],
  ['connexdatabase',['ConnexDataBase',['../da/d49/classfilter_1_1data_1_1_connex_data_base.html',1,'filter::data']]],
  ['connexinput',['ConnexInput',['../df/ddc/classfilter_1_1data_1_1_connex_input.html',1,'filter::data']]],
  ['connexinput_3c_20filter_3a_3adata_3a_3adata_20_3e',['ConnexInput&lt; filter::data::Data &gt;',['../df/ddc/classfilter_1_1data_1_1_connex_input.html',1,'filter::data']]],
  ['connexoutput',['ConnexOutput',['../d6/ddc/classfilter_1_1data_1_1_connex_output.html',1,'filter::data']]],
  ['connexoutput_3c_20filter_3a_3adata_3a_3adata_20_3e',['ConnexOutput&lt; filter::data::Data &gt;',['../d6/ddc/classfilter_1_1data_1_1_connex_output.html',1,'filter::data']]],
  ['connexoutput_3c_20filter_3a_3adata_3a_3aimagedata_20_3e',['ConnexOutput&lt; filter::data::ImageData &gt;',['../d6/ddc/classfilter_1_1data_1_1_connex_output.html',1,'filter::data']]],
  ['content',['Content',['../d8/d54/classhttp_1_1_server_base_1_1_content.html',1,'http::ServerBase&lt; socket_type &gt;::Content'],['../dd/d5f/classhttp_1_1_content.html',1,'http::Content']]],
  ['contrast',['Contrast',['../d8/d7f/classfilter_1_1algos_1_1_contrast.html',1,'filter::algos']]],
  ['copyobject',['CopyObject',['../d8/d9c/classfilter_1_1data_1_1_copy_object.html',1,'filter::data']]],
  ['crop',['Crop',['../dd/d88/classfilter_1_1_algos_1_1_crop.html',1,'filter::Algos']]],
  ['cropper',['Cropper',['../d5/d9d/classfilter_1_1algos_1_1_cropper.html',1,'filter::algos']]],
  ['crypto',['Crypto',['../d9/d0c/class_simple_web_1_1_crypto.html',1,'SimpleWeb']]],
  ['cvcropperdata',['CVCropperData',['../db/d03/classfilter_1_1algos_1_1_cropper_1_1_c_v_cropper_data.html',1,'filter::algos::Cropper']]]
];
